{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "crasher.svcname" . }}
  labels:
    app: {{ template "crasher.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: 8081
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "crasher.name" . }}
    release: {{ .Release.Name }}
{{- end -}}